import {
  Sparkles,
  CheckCircle,
  XCircle,
  DollarSign,
} from "lucide-react";

function RecommendationCard({ darkMode }) {
  return (
    <div
      className={`rounded-2xl shadow-sm p-6 mt-8 border transition-all duration-300 ${
        darkMode
          ? "bg-gray-900 border-gray-700"
          : "bg-white border-gray-200"
      }`}
    >
      <div className="flex items-center gap-3 mb-6">
        <div className="bg-yellow-100 p-3 rounded-xl">
          <Sparkles className="text-yellow-600" />
        </div>

        <div>
          <h2
            className={`text-2xl font-bold ${
              darkMode ? "text-white" : "text-gray-800"
            }`}
          >
            AI Recommendations
          </h2>

          <p
            className={`${
              darkMode ? "text-gray-400" : "text-gray-500"
            }`}
          >
            Rightsizing suggestions generated by AI.
          </p>
        </div>
      </div>

      {/* Recommendation 1 */}

      <div
        className={`border rounded-xl p-5 mb-5 transition ${
          darkMode
            ? "border-gray-700 hover:bg-gray-800"
            : "hover:bg-gray-50"
        }`}
      >
        <div className="flex justify-between items-start">
          <div>
            <h3
              className={`text-lg font-semibold ${
                darkMode ? "text-white" : ""
              }`}
            >
              Resize EC2 Instance
            </h3>

            <p
              className={`mt-2 ${
                darkMode ? "text-gray-400" : "text-gray-500"
              }`}
            >
              Current: t3.large
            </p>

            <p
              className={`${
                darkMode ? "text-gray-400" : "text-gray-500"
              }`}
            >
              Suggested: t3.medium
            </p>

            <div className="flex items-center gap-2 mt-4">
              <DollarSign
                className="text-green-600"
                size={20}
              />

              <span className="font-semibold text-green-600">
                Save $180/month
              </span>
            </div>
          </div>

          <div className="bg-blue-100 text-blue-700 px-3 py-1 rounded-full text-sm font-medium">
            High Impact
          </div>
        </div>

        <div className="flex gap-4 mt-6">
          <button className="flex items-center gap-2 bg-green-600 hover:bg-green-700 text-white px-5 py-2 rounded-lg transition">
            <CheckCircle size={18} />
            Approve
          </button>

          <button className="flex items-center gap-2 bg-red-600 hover:bg-red-700 text-white px-5 py-2 rounded-lg transition">
            <XCircle size={18} />
            Reject
          </button>
        </div>
      </div>

      {/* Recommendation 2 */}

      <div
        className={`border rounded-xl p-5 transition ${
          darkMode
            ? "border-gray-700 hover:bg-gray-800"
            : "hover:bg-gray-50"
        }`}
      >
        <div className="flex justify-between items-start">
          <div>
            <h3
              className={`text-lg font-semibold ${
                darkMode ? "text-white" : ""
              }`}
            >
              Delete Idle EBS Volume
            </h3>

            <p
              className={`mt-2 ${
                darkMode ? "text-gray-400" : "text-gray-500"
              }`}
            >
              Unused storage detected for more than 30 days.
            </p>

            <div className="flex items-center gap-2 mt-4">
              <DollarSign
                className="text-green-600"
                size={20}
              />

              <span className="font-semibold text-green-600">
                Save $40/month
              </span>
            </div>
          </div>

          <div className="bg-green-100 text-green-700 px-3 py-1 rounded-full text-sm font-medium">
            Medium Impact
          </div>
        </div>

        <div className="flex gap-4 mt-6">
          <button className="flex items-center gap-2 bg-green-600 hover:bg-green-700 text-white px-5 py-2 rounded-lg transition">
            <CheckCircle size={18} />
            Approve
          </button>

          <button className="flex items-center gap-2 bg-red-600 hover:bg-red-700 text-white px-5 py-2 rounded-lg transition">
            <XCircle size={18} />
            Reject
          </button>
        </div>
      </div>
    </div>
  );
}

export default RecommendationCard;